version: '3.8'
services:
  mongo-db:
    container_name: mongo-db
    image: mongo:7
    ports:
      - '27018:27017'
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
volumes:
  mongo-data:

